### ISSUE TITLE
New release to prevent downstream issues due to deleted tag

### ISSUE THREAD

**Issue by avorima** [ionos-enterprise/ionos-enterprise-sdk-go#86]
Rolling back a feature is completely fine, but doing it by deleting a tag is a really bad practice.
Please create a v5.0.30 tag without the changes from v5.0.29.

**Comment by pennycoders** [comment]
Hi @avorima,

Yes, I am aware, unfortunately due to a timing issue the v5.0.29 tag was already created too early. Now the change has been updated and everything is as it should be. Thank you very much for the input.

Thanks,

Alex
